### ISSUE TITLE
Package install not working

### ISSUE THREAD

**Issue by hari-rangarajan** [amadeus4dev/amadeus-node#11]
Packaging broken; not installing the module?

$ npm install amadeus4dev/amadeus-node --save
npm WARN tp-algorithm-v2@1.0.0 No repository field.

+ amadeus@1.0.1
added 1 package from 2 contributors in 3.927s
[+] no known vulnerabilities found [15 packages audited]

$ ls -alt  node_modules/amadeus/
total 72
drwxrwxr-x  2 hari hari 4096 May 14 22:54 .
drwxrwxr-x 15 hari hari 4096 May 14 22:54 ..
-rw-rw-r--  1 hari hari 2309 May 14 22:54 package.json
-rw-rw-r--  1 hari hari  791 Oct 26  1985 CHANGELOG.md
-rw-rw-r--  1 hari hari 1085 Oct 26  1985 LICENSE
-rw-rw-r--  1 hari hari 8027 Oct 26  1985 README.md
-rw-rw-r--  1 hari hari  534 Oct 26  1985 .travis.yml

$ node amadeus_test.js 
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'amadeus'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)

**Comment by cbetta** [comment]
@hari-rangarajan please don't install from GitHub but from npmjs.com. GitHub only contains the pre-babelfied source, not the actual transpiled library. 

```
npm install amadeus --save
```
