### ISSUE TITLE
Add support for Travel Restrictions API 

### ISSUE THREAD

**Issue by tsolakoua** [amadeus4dev/amadeus-node#112]

**Comment by harshabikkavilli** [comment]
Any update when this can be available ? Thank you.

**Comment by tsolakoua** [comment]
We don't have a specific date to commit right now of when this will be added. However, as described in the readme, you can make any arbitrary API call directly with the .get method for endpoints that are not supported yet. For example, for travel restrictions you can do:

```js
amadeus.client.get('/v1/duty-of-care/diseases/covid19-area-report, { countryCode: 'ES' });
```
