### ISSUE TITLE
amadeus hotelrating api shows error

### ISSUE THREAD

**Issue by Mohamedarsath** [amadeus4dev/amadeus-node#116]
## Description
In  hotel-sentiments api throws error
'{"errors":[{"status":415,"code":477,"title":"INVALID FORMAT","detail":"Accept header value specified in the request is not supported"}]}'
i am using this syntax,
amadeus.client.get('/v2/e-reputation/hotel-sentiments',{hotelIds :"ADNYCCTB"});

**Comment by tsolakoua** [comment]
Thanks for reporting the issue - it's on the API side. A workaround is to add a header to the request `Accept: application/json`.
