### ISSUE TITLE
Old token will be taken from cache even when Amadeus user credentials change

### ISSUE THREAD

**Issue by kerstinSimoneM** [amadeus4dev/amadeus-node#120]
## Description

If you want to switch to another Amadeus account, you change the credentials but instead of requesting a new token, it seems like the old token is used from the first Amadeus account. How is it possible to ignore the old token In order to get a correct token for the new Amadeus account?

## Steps to Reproduce

1. Use the credentials from a second Amadeus account
2. Run your project

__Expected Behavior:__ I would expect the package to request a new token since it is a new Amadeus account

__Actual Behavior:__ It seems like the old existing token from the first Amadeus account is used which produces the error `Invalid token`

__Stable Behavior?__ 100%

## Versions

Node: v14.8.0
npm: 6.14.15
OS: macOS Big Sur 

## Checklist

Please make sure you checked the following:

* Are you running any of the current [Node LTS versions](https://nodejs.org/en/about/releases/)?
* Did you download the latest version of this library?

**Comment by minjikarin** [comment]
Hello! I have tried with 2 different API keys (from different Amadeus accounts) and it is working as expected that I have received 2 different tokens to proceed with the APIs. = generate a new token if I use a different key.

can you please share the log if you still face the issue?

**Comment by minjikarin** [comment]
i close this issue since there is no response for a month :)
