### ISSUE TITLE
how to get airlines name

### ISSUE THREAD

**Issue by abhilash007** [amadeus4dev/amadeus-node#128]

**Comment by minjikarin** [comment]
Hello, the question is not clear enough, but: you can get airline codes in the API response and at the end of the response, you will find the airline code with airline names under 'Dictionaries'. 

for example in Flight Offers Search response  : 

        "carriers": {
            "AC": "AIR CANADA",
            "UA": "UNITED AIRLINES",
            "LX": "SWISS INTERNATIONAL AIR LINES"
        }
