### ISSUE TITLE
Proxy Server Settings

### ISSUE THREAD

**Issue by ermadhan** [amadeus4dev/amadeus-node#129]
## Description

How to connect behind proxy server to Amadeus APIs? I am not able to find the documentation around this.

## Steps to Reproduce

1. Take any of the samples provided in Git Repository.
2.  Execute the program

__Expected Behavior:__ Output should be coming as expected for the API

__Actual Behavior:__ Network error is returned

## Versions
Node 14

## Checklist

**Comment by minjikarin** [comment]
@ermadhan, Apologize for late response of this issue. 

Would you be able to clarify further what is your ultimate goal? 
what is the reason that you would like to connect with proxy instead of actual calling of APIs?

**Comment by minjikarin** [comment]
@ermadhan , I would appreciate for your input otherwise i will close the issue in a week :) thanks
