### ISSUE TITLE
Flight inspiration search 404

### ISSUE THREAD

**Issue by juanihno** [amadeus4dev/amadeus-node#166]
## Description

[Im getting error 404 in flight inspiration search in test mode even in the try it out from the official Amadeus page

## Steps to Reproduce

1. [First step]
2. [Second step]
3. [and so on...]

__Expected Behavior:__ [What you expect to happen]

__Actual Behavior:__ [What actually happens]

__Stable Behavior?__ [What percentage of the time does it reproduce?]

## Versions

[What version of Node/NPM are you running? What Operating System are you on?]

## Checklist

Please make sure you checked the following:

* Are you running any of the current [Node LTS versions](https://nodejs.org/en/about/releases/)?
* Did you download the latest version of this library?

**Comment by minjikarin** [comment]
hello @juanihno, this issue has been resolved since yesterday 12 September. issue closed. thank you!
