### ISSUE TITLE
Not possbile to call locations.hotels.byCity.get

### ISSUE THREAD

**Issue by renatoBrancato** [amadeus4dev/amadeus-node#198]
## Description

Not possbile to call locations.hotels.byCity.get with rating param as mentioned as the documentation permit:
https://developers.amadeus.com/self-service/category/hotels/api-doc/hotel-list/api-reference

## Steps to Reproduce

call node funcion like:

amadeus.referenceData.locations.hotels.byCity.get({
    cityCode: city,
    ratings:'1,2'

  }

__Expected Behavior:__ retrive hotels

__Actual Behavior:__ empty object returned

__Stable Behavior?__ [What percentage of the time does it reproduce?]

**Comment by minjikarin** [comment]
Hello @renatoBrancato, which city code did you use? 

I have managed to get a response by calling as below. 

`amadeus.referenceData.locations.hotels.byCity.get({
  cityCode: "PAR",
  ratings:'1,2'})`

**Comment by minjikarin** [comment]
Closed the issue since no response :)
