### ISSUE TITLE
Flight Inspiration Endpoint not supporting BER and FCO as origin on production

### ISSUE THREAD

**Issue by vneri** [amadeus4dev/amadeus-node#199]
## Description

Hi everyone, I am using the Flight Inspiration Endpoint (from Node, but also tested from Postman).
Example code:

`
amadeus.shopping.flightDestinations.get({
  origin: 'BER'
}).then((destinationOffersResponse) => {
  console.dir(destinationOffersResponse, { depth: null });
}).catch((error) => {
  console.dir(error);
}).finally(() => {
  console.log('done');
});
`

When calling it with MAD or PAR, the API works as expected. When called with FCO or BER, I receive an error.
Please note that I am on production.
![grafik](https://github.com/amadeus4dev/amadeus-node/assets/4535733/cb15f675-4cfa-465a-93c5-7ed7ca24f041)

## Steps to Reproduce

1. [First step]
Get production keys
3. [Second step]
Call the Flight Inspiration Endpoint with the origin set to BER

__Expected Behavior:__ [What you expect to happen]
Return the flight deals for the given airports (BER, FCO)

__Actual Behavior:__ [What actually happens]
HTTP ERROR 500
description: [
    {
      status: 500,
      code: 141,
      title: 'SYSTEM ERROR HAS OCCURRED',
      detail: 'ORIGIN AND DESTINATION NOT SUPPORTED'
    }
  ],
  code: 'ServerError'

![grafik](https://github.com/amadeus4dev/amadeus-node/assets/4535733/58c726d2-9215-449f-a59b-582320f1a52b)

__Stable Behavior?__ [What percentage of the time does it reproduce?]
100%

## Versions

[What version of Node/NPM are you running? What Operating System are you on?]
Tried it with the latest Node package and also on Postman

## Checklist

Please make sure you checked the following:

* Are you running any of the current [Node LTS versions](https://nodejs.org/en/about/releases/)?
Node v19.3.0
* Did you download the latest version of this library?
└── amadeus@9.0.0

Thanks for your help!

**Comment by vneri** [comment]
I just ran the API againts all majour German airports, and apparently only MUC and FRA are supported - does anyone know why?

**Comment by minjikarin** [comment]
Closed the issue due to non activity

**Comment by vneri** [comment]
Hi Minji, thank you for your reply - does this apply also to this endpoint?
https://developers.amadeus.com/self-service/category/flights/api-doc/flight-cheapest-date-search/api-reference

I have tried finding the cheapest connection from Berlin to Abu-Dhabi

```
amadeus.shopping.flightDates.get({
    origin: 'BER',
    destination: 'AUH',
}).then((destinationOffersResponse) => {
    console.dir(destinationOffersResponse, { depth: null });
}).catch((error) => {
    console.dir(error.response.body);
}).finally(() => {
    console.log('done');
});
```

but the result unfortunately brings the same error: 
'{"errors":[{"status":500,"code":141,"title":"SYSTEM ERROR HAS OCCURRED","detail":"ORIGIN AND DESTINATION NOT SUPPORTED"}]}'

I even tried LEJ (Leipzig, which even flies directly).

When trying with FRA (Frankfurt) I get another type of error though:
'{"errors":[{"status":404,"code":6003,"title":"ITEM/DATA NOT FOUND OR DATA NOT EXISTING","detail":"No price result found"},{"status":404,"code":6003,"title":"ITEM/DATA NOT FOUND OR DATA NOT EXISTING","detail":"No price results found for input combined criteria"}]}'

So in the case of Berlin we get a 500 "ORIGIN NOT SUPPORTED" and in the case of Frankfurt we get a 404 "NO DATA EXISTING".
Is the API behaving incorrectly here? Why is there such a problem with German origins?

We are trying to build a flight inspiration service (basically answering the question "what is a good flight deal in the next months from my starting origin?". If these flight aggregation endpoints do not work, we are left with polling for every origin-destination and date combination, resulting in a huge amount of API calls.

Thanks for your support!

**Comment by garethjcox** [comment]
Hi

I am dealing with the same issues here but for the AMS-JNB combination. Did you find any work arounds? I have tried multiple ways of the 3 letter city/airport code but it does not seem to work for me even when in prod.

Thanks

**Comment by vneri** [comment]
Hi Gareth, we stopped the project, so I didn't check anymore
