### ISSUE TITLE
Issue with token expiration handling

### ISSUE THREAD

**Issue by csimpi** [amadeus4dev/amadeus-node#22]
## Description

I'm implementing Amadeus with AngularJS. I used the `amadeus-node` as a reference, especially regarding the token expiration-refreshing flow.
After I read the code I pointed out there might be an issue with the token handling here:
`this.expiresAt = Date.now() + response.result['expires_in'];`

- According to the OAuth's doc, the `expires_in` is the lifetime in **seconds** of the access token.
- The `Date.now()` method returns the number of **milliseconds** elapsed since January 1, 1970.

## Steps to Reproduce

No need to reproduce

__Expected Behavior:__ 
Correct expiration time:
`this.expiresAt = Date.now() + (response.result['expires_in']*1000);`

__Actual Behavior:__ 
`this.expiresAt = Date.now() + response.result['expires_in'];` returns wrong expiration time due to the mixed format (ms + s).

__Stable Behavior?__ [What percentage of the time does it reproduce?]

## Versions

[What version of Node/NPM are you running? What Operating System are you on?]

## Checklist

Please make sure you checked the following:

* Are you running Node 2.2+?
* Did you download the latest version of this gem?

**Comment by anthonyroux** [comment]
You are right, but reproduced: 

> ╰─ node
> Date.now()
1557331863449 = Wed May 08 2019 18:11:03
> Date.now() + 1799
1557331871483 = Wed May 08 2019 18:11:11
