### ISSUE TITLE
a promise was rejected with a non-error

### ISSUE THREAD

**Issue by gaieges** [amadeus4dev/amadeus-node#23]
## Description

Two unexpected / unnecessary warnings in the handling of promises (looks like related to a network error):

```
bluebird.js?f684:1564 Warning: a promise was rejected with a non-error: [object Object]    at EventEmitter.eval (webpack-internal:///./node_modules/amadeus/lib/amadeus/client.js:253:18)    at EventEmitter.emit (webpack-internal:///./node_modules/node-libs-browser/node_modules/events/events.js:146:5)    at Listener.eval (webpack-internal:///./node_modules/amadeus/lib/amadeus/client/listener.js:183:24)    at exports.IncomingMessage.emit (webpack-internal:///./node_modules/node-libs-browser/node_modules/events/events.js:146:5)    at eval (webpack-internal:///./node_modules/stream-http/lib/response.js:27:9)    at Item.run (webpack-internal:///./node_modules/process/browser.js:153:14)    at drainQueue (webpack-internal:///./node_modules/process/browser.js:123:42)
printWarning @ bluebird.js?f684:1564
formatAndLogError @ bluebird.js?f684:1280
warn @ bluebird.js?f684:1175
Promise._warn @ bluebird.js?f684:771
Promise._rejectCallback @ bluebird.js?f684:3256
(anonymous) @ bluebird.js?f684:3271
(anonymous) @ client.js?9cbe:253
emit @ events.js?7e25:146
(anonymous) @ listener.js?2211:183
emit @ events.js?7e25:146
(anonymous) @ response.js?c90b:27
Item.run @ browser.js?f28c:153
drainQueue @ browser.js?f28c:123
setTimeout (async)
runTimeout @ browser.js?f28c:41
process.nextTick @ browser.js?f28c:143
nextTick @ index.js?966d:26
resume @ _stream_readable.js?8b77:783
Readable.resume @ _stream_readable.js?8b77:775
Readable.on @ _stream_readable.js?8b77:745
onResponse @ listener.js?2211:60
emit @ events.js?7e25:146
ClientRequest._connect @ request.js?925e:268
(anonymous) @ request.js?925e:159
Promise.then (async)
ClientRequest._onFinish @ request.js?925e:157
(anonymous) @ request.js?925e:62
emit @ events.js?7e25:146
finishMaybe @ _stream_writable.js?5bc2:630
afterWrite @ _stream_writable.js?5bc2:492
afterTick @ index.js?966d:40
Item.run @ browser.js?f28c:153
drainQueue @ browser.js?f28c:123
setTimeout (async)
runTimeout @ browser.js?f28c:41
process.nextTick @ browser.js?f28c:143
nextTick @ index.js?966d:39
onwrite @ _stream_writable.js?5bc2:480
WritableState.onwrite @ _stream_writable.js?5bc2:180
ClientRequest._write @ request.js?925e:275
doWrite @ _stream_writable.js?5bc2:428
writeOrBuffer @ _stream_writable.js?5bc2:417
Writable.write @ _stream_writable.js?5bc2:334
execute @ client.js?9cbe:203
unauthenticatedRequest @ client.js?9cbe:184
loadAccessToken @ access_token.js?50dc:134
emitOrLoadAccessToken @ access_token.js?50dc:96
bearerToken @ access_token.js?50dc:56
request @ client.js?9cbe:150
get @ client.js?9cbe:106
get @ locations.js?d315:69
getAirports @ TravelData.js?c2e7:31
AirportSelector._this.populateAirports @ AirportSelector.js?4781:41
(anonymous) @ AirportSelector.js?4781:29
setTimeout (async)
AirportSelector._this.mouseDown @ AirportSelector.js?4781:28
handleChange @ Autocomplete.js?ffc0:128
callCallback @ react-dom.development.js?61bb:149
invokeGuardedCallbackDev @ react-dom.development.js?61bb:199
invokeGuardedCallback @ react-dom.development.js?61bb:256
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js?61bb:270
executeDispatch @ react-dom.development.js?61bb:561
executeDispatchesInOrder @ react-dom.development.js?61bb:583
executeDispatchesAndRelease @ react-dom.development.js?61bb:680
executeDispatchesAndReleaseTopLevel @ react-dom.development.js?61bb:688
forEachAccumulated @ react-dom.development.js?61bb:660
runEventsInBatch @ react-dom.development.js?61bb:816
runExtractedEventsInBatch @ react-dom.development.js?61bb:824
handleTopLevel @ react-dom.development.js?61bb:4826
batchedUpdates$1 @ react-dom.development.js?61bb:20233
batchedUpdates @ react-dom.development.js?61bb:2151
dispatchEvent @ react-dom.development.js?61bb:4905
(anonymous) @ react-dom.development.js?61bb:20284
unstable_runWithPriority @ scheduler.development.js?3069:255
interactiveUpdates$1 @ react-dom.development.js?61bb:20283
interactiveUpdates @ react-dom.development.js?61bb:2170
dispatchInteractiveEvent @ react-dom.development.js?61bb:4882
```

## Steps to Reproduce

```js
class TravelData {
  constructor() {
    const client = new Amadeus({
      clientId: config.amadeus.key,
      clientSecret: config.amadeus.secret
    });

    this.client = client;
  }

  getAirports(prefix) {
    return this.client.referenceData.locations.get({
      keyword: prefix,
      subType: Amadeus.location.airport
    }).then(resp => {
      // console.log(resp);
      return resp.data;
    }).catch(console.log)
  }
}

new TravelData().getAirports('aus');
```

__Expected Behavior:__ Success with no warnings

__Actual Behavior:__ Warnings

__Stable Behavior?__ 100%

## Versions

- Macosx Mojave
- Chrome `73.0.3683.103`
- Amadeus-node `3.1.0`
- node `v11.14.0`
- webpack `4.29.5`

## Checklist

Please make sure you checked the following:

* Are you running Node 2.2+? uh, yeah
* Did you download the latest version of this gem? not any gems involved here..

**Comment by akshitsingla** [comment]
Hello @gaieges ,
Could you please share some more information? I'm looking for 
- the version of bluebird available in your environment,
- if you're running the app inside a docker container,
- since it was generated due to a NewtorkError, could you please elaborate what was the issue (e.g. disconnected from internet, etc.)?

**Comment by gaieges** [comment]
- `bluebird@3.5.3`
- Not running app in docker, but shouldn't have much of an affect (it's a webapp built built by webpack and run in the browser)
- As far as I could tell there was no actual error, the message popped up twice in the normal functioning of the client (ie I was able to make the call, get the data back, and use it in subsequent processing)

**Comment by akshitsingla** [comment]
Hello @gaieges ,
Firstly, the recommended site to integrate this SDK is on server-side to avoid leaking credentials.

Regarding the warning: 
I'm unable to reproduce it on the server-side. Could you please share a step-by-step guide if you're facing the same issue there? If not, we can close this issue since client-side implementation is not supported.

**Comment by gaieges** [comment]
Credentials aside, are you saying this module doesn't support being run in a browser? Is that documented somewhere?

**Comment by akshitsingla** [comment]
You are right, our recommendation is to not use the SDK on the front-end side because of the potential security issue with the API Key/Secret.

The module is tested to work in the backend, but so far, it should work fine with frontend as well. If I understand well, it works for you but you are facing the warning. 
Based on our investigation, updating the type of object thrown as error might solve the problem (http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-rejected-with-a-non-error). This will require some changes in the SDK. As we have new APIs coming and our priority is to integrate them in the SDK, we will put a lower priority to this ticket.
 
All contributions are more than welcome :)

**Comment by gaieges** [comment]
Yeah don't worry about the credential piece, I have that covered.  

It DOES seem to work in a browser just wanted to flag to you that warning that I saw in it.  I've seen some errors like this before in bluebird and the thing you described helped me as well.  I get this is low priority, no worries!
