### ISSUE TITLE
Chose market (point of sale) from which flight rates are taken 

### ISSUE THREAD

**Issue by fcaivano** [amadeus4dev/amadeus-node#33]
I think the title is clear enough but just in case.

When I do a Flight Offers request

`amadeus.client.get('/v2/shopping/flight-offers', params)`

The rates on the response are not the ones I get from other GDS on a local search (Argentina)

Is there a way to change the market for which the requests are made? Because the price difference is quite high in some cases, and when I check the fare details the itinerary might be the same but the fare code is different

From what I’ve checked prices correspond more to a Spain search/market (if I do a conversion and compare), but still not sure.

**Comment by tsolakoua** [comment]
It's not possible in Self-Service APIs to change the point of sale for which the request are made. In production environment the point of sale assigned depends on the location each user declares.
