### ISSUE TITLE
Add support for Flight Create Orders

### ISSUE THREAD

**Issue by anthonyroux** [amadeus4dev/amadeus-node#36]

**Comment by greeven** [comment]
I'll second that.
Is there an ETA available?

**Comment by anthonyroux** [comment]
It's hard to commit on any dates on our side as we are quite busy, we will do our best to update the SDK ASAP. Otherwise all contributions are very welcome :).

**Comment by akshitsingla** [comment]
https://github.com/amadeus4dev/amadeus-node/pull/51
