### ISSUE TITLE
Uncaught ReferenceError: require is not defined when initializing amadeus

### ISSUE THREAD

**Issue by JohnnyLee6** [amadeus4dev/amadeus-node#65]
## Description

When running my javascript code on Chrome and initialize amadeus, got the error:
    Uncaught ReferenceError: require is not defined

## Steps to Reproduce

I used "npm install amadeus --save"
and wrote the below function in javascript:

function fetchHotelInfo() {
    let Amadeus = require('amadeus');
    let amadeus = new Amadeus({
        clientId: '',
        clientSecret: ''
    });
    amadeus.referenceData.urls.checkinLinks.get({
        airlineCode: 'BA'
    }).then(function(response){
        console.log(response.body);   //=> The raw body
        console.log(response.result); //=> The fully parsed result
        console.log(response.data);   //=> The data attribute taken from the result
    }).catch(function(error){
        console.log(error.response); //=> The response object with (un)parsed data
        console.log(error.response.request); //=> The details of the request made
        console.log(error.code); //=> A unique error code to identify the type of error
    });

}

__Expected Behavior:__ something should be logged

__Actual Behavior:__ Uncaught ReferenceError: require is not defined

__Stable Behavior?__ always

## Versions

NPM: 6.14.4, MAC 10.15.4

## Checklist

Please make sure you checked the following:

* Are you running Node 6?  yes
* Did you download the latest version of this library?  amadeus 4.0.0
<img width="382" alt="Screen Shot 2020-04-26 at 11 04 22 PM" src="https://user-images.githubusercontent.com/39628854/80330112-495f6980-8812-11ea-898d-0ccbdcb8b566.png">

![Screen Shot 2020-04-26 at 11 02 51 PM](https://user-images.githubusercontent.com/39628854/80330050-1b7a2500-8812-11ea-8e16-0d026eed4646.png)

**Comment by akshitsingla** [comment]
Hello Johny,

Firstly, `Uncaught ReferenceError: require is not defined` is not an SDK related issue.

Here's a pointer to the probable cause for that error:
It seems like you're running your JS application in a Chrome (browser) runtime environment; while it is built to be running in a node runtime environment.

**Comment by JohnnyLi13** [comment]
> Hello Johny,
> 
> Firstly, `Uncaught ReferenceError: require is not defined` is not an SDK related issue.
> 
> Here's a pointer to the probable cause for that error:
> It seems like you're running your JS application in a Chrome (browser) runtime environment; while it is built to be running in a node runtime environment.

Many Thanks! Tried several packages to make it run on the browser side. Hard to make them work. Figured it's actually better to have it run on the server side. Thank you!
