### ISSUE TITLE
Typescript Types

### ISSUE THREAD

**Issue by lifeofdubem** [amadeus4dev/amadeus-node#73]
## Description

This package is missing TypeScript Types defination

**Comment by akshitsingla** [comment]
Hello @lifeofdubem ,

Thank you for your interest in the Amadeus For Developers Node SDK. 

At this moment, we do not support TypeScript and I shall mark this as a low-priority enhancement. 
Having said that, we happily accept any contributions from the open-source community and would be delighted to help, if you're interested in contributing to the SDK with this.
The [Contributor's Guide](https://github.com/amadeus4dev/amadeus-node/blob/master/.github/CONTRIBUTING.md) can be a good resource to start from.

**Comment by deldrid1** [comment]
+1 for TypeScript definitions.

@akshitsingla - is there any chance that we can get a consolidated OpenAPI / Swagger spec to build our own if this is a `wontfix`?

**Comment by ireznik** [comment]
@akshitsingla would it help if I open a PR which migrates existing code to typescript with running tests but major any typings as a draft to move to typescript?

**Comment by minjikarin** [comment]
Hello! if you have the enhancement to typescript (sorry for late but if it is still valid :)), I suggest you open a new issue following the [contribution guide](https://github.com/amadeus4dev/amadeus-node/blob/master/.github/CONTRIBUTING.md#do-you-intend-to-add-a-new-feature-or-change-an-existing-one)! sounds very interesting! thanks for the interest and your activeness!

**Comment by jabrena** [comment]
This repository is not based on Typescript.
For that reason, we are going to close this issue.

Juan Antonio
