### ISSUE TITLE
Error missing module while implementing amadeus-node into angular project

### ISSUE THREAD

**Issue by r-k-o-l** [amadeus4dev/amadeus-node#85]
## Description

I gett the error "Module not found: Error: Can't resolve 'http'" while building an angular project with amadeus-node.

## Steps to Reproduce

1. Create new angular project with "ng new my-app-name"
2. Install amadeus-node with "npm install amadeus --save"
3. Import to app.component.ts with "import * as Amadeus from 'amadeus';"
4. Create instance of class Amadeus in ngOnInit of app.component.ts
5. Start with "ng s -o" from the visual studio code terminal.

![image](https://user-images.githubusercontent.com/54362896/90931043-1e6dd680-e3fc-11ea-8cbc-10747a56722e.png)

__Expected Behavior:__ The app starts in my default browser.

__Actual Behavior:__ Errors in the terminal at the end of the build:
ERROR in ./node_modules/amadeus/lib/amadeus/client/validator.js
Module not found: Error: Can't resolve 'http' in 'd:\workspace\my-app-name\node_modules\amadeus\lib\amadeus\client'

As soon as I remove the Instance of class Amadeus everything is fine.

![image](https://user-images.githubusercontent.com/54362896/90930659-51639a80-e3fb-11ea-8c89-e5031b443f43.png)

__Stable Behavior?__ 100%

## Versions
Windows 10 Home x64: 10.0.18362 Build 18362
Visual Studio Code: 1.48.1
Node.js: 12.18.3
Angular CLI: 10.0.6
NPM: 6.14.6
amadeus-node: 5.2.0

## Checklist
No, I'm not running node 6 and yes, I've downloaded the newest version of this library (as you can see above).
As far as I can see, all necessary files of the package are where they should be.
![image](https://user-images.githubusercontent.com/54362896/90930475-f8940200-e3fa-11ea-8346-b8a2bdaca387.png)

**Comment by alnacle** [comment]
Hey! Thanks for reporting this issue. The SDK is not designed to work on client-side frameworks like Angular (you can see that Angular cannot resolve the http-node dependency from amadeus-sdk) but on nodejs applications.

By the way, we have never consumed the SDK within a Typescript application. I believe it's not going to work out-of-the-box as it needs to provide a type declaration file.

**Comment by r-k-o-l** [comment]
okay, then excuse me for asking ;)
