### ISSUE TITLE
Suggestion to update the ```departureDate``` in README

### ISSUE THREAD

**Issue by kazewind22** [amadeus4dev/amadeus-node#87]
## Description

The ```departureDate``` in getting started code snippet is outdated and causes ClientError.
It would be nice if the date can be set to some future dates. :D

## Steps to Reproduce
```
var Amadeus = require('amadeus');

var amadeus = new Amadeus({
  clientId: 'REPLACE_BY_YOUR_API_KEY',
  clientSecret: 'REPLACE_BY_YOUR_API_SECRET'
});

amadeus.shopping.flightOffersSearch.get({
    originLocationCode: 'SYD',
    destinationLocationCode: 'BKK',
    departureDate: '2020-08-01',
    adults: '2'
}).then(function(response){
  console.log(response.data);
}).catch(function(responseError){
  console.log(responseError.code);
});
```
__Expected Behavior:__ Response.data

__Actual Behavior:__ ClientError

**Comment by tsolakoua** [comment]
Thanks a lot @kazewind22 for raising the issue. The code snippet has been updated :)
