### ISSUE TITLE
Question: Optional/Required fields in responses

### ISSUE THREAD

**Issue by Zeliret** [amadeus4dev/amadeus-node#93]
Hi there! 
I'm sorry if it is not appropriate to ask questions here, but I consider to use this service in my project and would like to know if there are any list of fields which a required in any response? 
So, for example for the city autocomplete request, can I trust that all fields of the object will be there or some of them might be absent (optional) or even all fields are optional?

**Comment by anthonyroux** [comment]
Hey, you can find the list of parameters in the API-reference documentation (here for [Airport & City Search](https://developers.amadeus.com/self-service/category/air/api-doc/airport-and-city-search/api-reference))


In the API reference, you can use the model to know what are the parameters returned and which ones are optional are not (thanks to the red *):
<img width="1476" alt="image" src="https://user-images.githubusercontent.com/713173/99888876-5c270900-2c50-11eb-8956-bfab6fd6fc6d.png">

You can access it at the end of the page using the **Models** drop-down menu as well. Everything looks "optional" for this API, I will ask the API dev team to check the specification to see if there is something wrong. But you can have the case where the API cannot find the city and will return an empty data array with a 200 status code.

Depending of the technical stack you will use, we have a couple of tutorials explaining how to use this API as auto-complete:
- [Airport & City Search MERN stack](https://developers.amadeus.com/blog/airport-autocomplete-app-with-the-mern-stack)
- [Airport & City Search with Django + JQuery](https://developers.amadeus.com/blog/django-jquery-ajax-airport-search-autocomplete)
- [Airport autocomplete using jQuery, Ajax, and the Amadeus Node SDK](https://developers.amadeus.com/blog/airport-autocomplete-jquery-ajax)

Hope it helps,
Anthony
